### ISSUE TITLE
quarkus 3.2.2 无法正常加载数据库

### ISSUE THREAD

**Issue by MrYang-Jia** [quarkiverse/quarkus-shardingsphere-jdbc#139]
环境版本
```
  <quarkus.platform.version>3.2.2.Final</quarkus.platform.version>
 <dependency>
      <groupId>io.quarkiverse.shardingsphere</groupId>
      <artifactId>quarkus-shardingsphere-jdbc</artifactId>
      <!-- 该版本在 3.2.2 版本的时候无法正常初始化数据库，所以暂时放弃 -->
     <version>2.0.0</version>
</dependency>
```

```
 @Inject
 DataSource dataSource;  // 动态注入时没有问题

    private void createAccountTable() throws SQLException {
        String sql = "CREATE TABLE t_account (account_id BIGINT NOT NULL AUTO_INCREMENT, user_id INT NOT NULL, status VARCHAR(50), PRIMARY KEY (account_id))";

        try (Connection connection = dataSource.getConnection();  // 执行到这里的时候 dataSource.getConnection();   会提示说没有init方法!!!导致无法初始化成功
                Statement statement = connection.createStatement()) {
            statement.executeUpdate(sql);
        }
    }

```

**Comment by MrYang-Jia** [comment]
我使用的案例就是示例项目里的，降低一个版本使用则没有问题，无问题的版本如下
```
    <quarkus.platform.version>2.16.8.Final</quarkus.platform.version>
    <dependency>
      <groupId>io.quarkiverse.shardingsphere</groupId>
      <artifactId>quarkus-shardingsphere-jdbc</artifactId>
      <version>1.0.2</version> 
     </dependency>
```

**Comment by zhfeng** [comment]
Thanks @MrYang-Jia can you share a reproducer project with this issue? The CI has passed with `3.2.2.Final`.

**Comment by MrYang-Jia** [comment]
please look this https://github.com/MrYang-Jia/demo-quarkus-shardingsphere
请看下这个链接的项目，其实我就是将该扩展到底下的 test 拿来做测试，才发现了这个问题，所以为了更好的复现我的情况，我还是单独发布了这个测试demo上来

```
2023-07-31 17:55:27,434 INFO  [com.zax.hik.HikariDataSource] (agroal-11) HikariPool-1 - Start completed.
2023-07-31 17:55:27,468 WARN  [io.agr.pool] (agroal-11) Datasource '<default>': Failed to create connection due to NoSuchMethodError
java.lang.NoSuchMethodError: org.yaml.snakeyaml.representer.Representer: method 'void <init>()' not found
	at org.apache.shardingsphere.infra.util.yaml.representer.ShardingSphereYamlRepresenter.<init>(ShardingSphereYamlRepresenter.java:42)
	at org.apache.shardingsphere.infra.util.yaml.YamlEngine.marshal(YamlEngine.java:113)
	at org.apache.shardingsphere.mode.metadata.persist.service.config.database.DataSourcePersistService.persist(DataSourcePersistService.java:56)
	at org.apache.shardingsphere.mode.metadata.persist.service.config.database.DataSourcePersistService.conditionalPersist(DataSourcePersistService.java:46)
	at org.apache.shardingsphere.mode.metadata.persist.MetaDataPersistService.persistConfigurations(MetaDataPersistService.java:93)
	at org.apache.shardingsphere.mode.manager.standalone.StandaloneContextManagerBuilder.persistConfigurations(StandaloneContextManagerBuilder.java:61)
	at org.apache.shardingsphere.mode.manager.standalone.StandaloneContextManagerBuilder.build(StandaloneContextManagerBuilder.java:50)
	at org.apache.shardingsphere.driver.jdbc.core.datasource.ShardingSphereDataSource.createContextManager(ShardingSphereDataSource.java:77)
	at org.apache.shardingsphere.driver.jdbc.core.datasource.ShardingSphereDataSource.<init>(ShardingSphereDataSource.java:65)
	at org.apache.shardingsphere.driver.api.ShardingSphereDataSourceFactory.createDataSource(ShardingSphereDataSourceFactory.java:93)
	at org.apache.shardingsphere.driver.api.yaml.YamlShardingSphereDataSourceFactory.createDataSource(YamlShardingSphereDataSourceFactory.java:153)
	at org.apache.shardingsphere.driver.api.yaml.YamlShardingSphereDataSourceFactory.createDataSource(YamlShardingSphereDataSourceFactory.java:95)
	at org.apache.shardingsphere.driver.jdbc.core.driver.DriverDataSourceCache.createDataSource(DriverDataSourceCache.java:51)

```

**Comment by MrYang-Jia** [comment]
> 谢谢@MrYang-Jia你能分享一个解决这个问题的重现项目吗？CI 已通过`3.2.2.Final`。
thanks,please look this  https://github.com/MrYang-Jia/demo-quarkus-shardingsphere

**Comment by zhfeng** [comment]
Well, I see. Thanks a lot for your reproducer!

I think this error message might be a known issue
```
2023-07-31 17:55:27,468 WARN  [io.agr.pool] (agroal-11) Datasource '<default>': Failed to create connection due to NoSuchMethodError
java.lang.NoSuchMethodError: org.yaml.snakeyaml.representer.Representer: method 'void <init>()' not found
```

It could be related to 
- https://github.com/apache/shardingsphere/pull/24636

So the work around is to stay with `snakeyaml:1.33` currently and wait the `shardingsphere` upgrading in the future.
